# Generated by Django 5.2 on 2026-01-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('pos', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='categories_tenant__114b0d_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='category',
            name='pos_devices',
            field=models.ManyToManyField(blank=True, help_text='POS devices where this category is available. Leave blank to make available on all devices in the branch.', related_name='categories', to='pos.posdevice'),
        ),
        migrations.AddField(
            model_name='product',
            name='pos_devices',
            field=models.ManyToManyField(blank=True, help_text='POS devices where this product is available. Leave blank to make available on all devices in the branch.', related_name='products', to='pos.posdevice'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'branch', 'name')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'branch', 'is_active', 'display_order'], name='categories_tenant__3ce045_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku',), name='unique_sku'),
        ),
    ]
