# Generated by Django 5.2 on 2026-01-30 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Device name (e.g., Counter 1, Drive-thru)', max_length=255)),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('tablet', 'Tablet'), ('desktop', 'Desktop POS'), ('mobile', 'Mobile'), ('kiosk', 'Self-Service Kiosk')], default='tablet', max_length=20)),
                ('serial_number', models.CharField(blank=True, help_text='Device serial number', max_length=255)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address', max_length=17)),
                ('model', models.CharField(blank=True, help_text='Device model (e.g., iPad Pro, Samsung Tab)', max_length=255)),
                ('auth_token', models.CharField(default=uuid.uuid4, help_text='Device authentication token', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('suspended', 'Suspended')], default='inactive', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'cashier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_devices', to='branches.branch')),
            ],
            options={
                'verbose_name': 'POS Device',
                'verbose_name_plural': 'POS Devices',
                'db_table': 'pos_devices',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('online', 'Device Online'), ('offline', 'Device Offline'), ('error', 'Error'), ('sale', 'Sale Transaction'), ('sync', 'Data Sync')], max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['branch', 'status'], name='pos_devices_branch__5f3f92_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id'], name='pos_devices_device__493bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='pos_devices_status_52e088_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['device', '-created_at'], name='device_logs_device__15f61f_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['log_type', '-created_at'], name='device_logs_log_typ_8e2afe_idx'),
        ),
    ]
