# Generated by Django 5.2 on 2026-01-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subscription_plan', models.CharField(choices=[('basic', 'Basic - 1 branch, 2 devices'), ('professional', 'Professional - 5 branches, 10 devices'), ('enterprise', 'Enterprise - Unlimited')], db_index=True, default='basic', max_length=20)),
                ('max_branches', models.IntegerField(default=1)),
                ('max_devices', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='tenants_email_46e4ef_idx')],
            },
        ),
    ]
