# Generated by Django 5.2 on 2026-01-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pos_devices',
            field=models.ManyToManyField(blank=True, help_text='POS devices this user has access to (for cashiers/branch managers)', related_name='operators', to='pos.posdevice'),
        ),
    ]
