# Generated by Django 5.2 on 2026-01-30 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Counter 1, Drive-thru', max_length=255)),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('tablet', 'Tablet'), ('desktop', 'Desktop'), ('mobile', 'Mobile')], default='tablet', max_length=50)),
                ('auth_token', models.CharField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('suspended', 'Suspended')], default='offline', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='branches.branch')),
            ],
            options={
                'verbose_name': 'POS Device',
                'verbose_name_plural': 'POS Devices',
                'db_table': 'pos_devices',
                'ordering': ['branch', 'name'],
                'indexes': [models.Index(fields=['branch', 'is_active'], name='pos_devices_branch__b0db9d_idx'), models.Index(fields=['device_id'], name='pos_devices_device__493bd4_idx')],
            },
        ),
    ]
