# Generated by Django 5.2 on 2026-02-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdevice',
            name='public_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
